name = "Unityper"
uuid = "a7c27f48-0311-42f6-a7f8-2c11e75eb415"
authors = ["Yingbo Ma <mayingbo5@gmail.com>, Chris Elrod <elrodc@gmail.com>, and contributors"]
version = "0.1.2"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
ConstructionBase = "1"
julia = "1.3"

[extras]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Setfield", "Test"]
